# Generated by Django 4.1.7 on 2023-05-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("size", models.CharField(max_length=30)),
                ("baseprice", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("finalprice", models.IntegerField()),
                ("stock", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("pic1", models.ImageField(upload_to="product")),
                (
                    "pic2",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="product"
                    ),
                ),
                (
                    "pic3",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="product"
                    ),
                ),
                (
                    "pic4",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="product"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Brandcategory",
            new_name="Brand",
        ),
        migrations.DeleteModel(
            name="productcategory",
        ),
        migrations.AddField(
            model_name="product",
            name="Brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.brand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="maincategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.maincategory"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.subcategory"
            ),
        ),
    ]
