# Generated by Django 4.1.7 on 2023-05-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_product_rename_brandcategory_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="brand"
            ),
        ),
    ]
