# Generated by Django 4.1.7 on 2023-05-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_alter_buyer_addressline1_alter_buyer_addressline2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="username",
        ),
    ]
