# Generated by Django 4.1.7 on 2023-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_remove_buyer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="username",
            field=models.CharField(default="", max_length=30),
        ),
    ]
