# Generated by Django 4.1.7 on 2023-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0011_checkout_checkoutproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproduct",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkoutproduct",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
