# Generated by Django 4.1.7 on 2023-05-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0014_alter_checkout_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Done")], default=1
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
