# Generated by Django 4.1.7 on 2023-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0015_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
