# Generated by Django 4.1.7 on 2023-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0016_alter_contact_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(default=-12233424),
        ),
    ]
