# Generated by Django 4.2.2 on 2023-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0018_checkout_rppid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
